db = db.getSiblingDB('gitquery');
db.createCollection('users');
db.createCollection('chat_sessions');
db.createCollection('user_interactions');
db.createCollection('recommendations');
db.users.createIndex({ 'user_id': 1 }, { unique: true });
db.users.createIndex({ 'username': 1 }, { unique: true });
db.users.createIndex({ 'email': 1 }, { unique: true });
db.chat_sessions.createIndex({ 'session_id': 1 }, { unique: true });
db.chat_sessions.createIndex({ 'user_id': 1 });
db.user_interactions.createIndex({ 'interaction_id': 1 }, { unique: true });
db.user_interactions.createIndex({ 'user_id': 1 });
db.user_interactions.createIndex({ 'repo_id': 1 });
db.recommendations.createIndex({ 'recommendation_id': 1 }, { unique: true });
db.recommendations.createIndex({ 'user_id': 1 });
db.recommendations.createIndex({ 'repo_id': 1 });
print(' MongoDB initialized');
