db = db.getSiblingDB('gitquery_cosmos');
db.createCollection('repositories');
db.createCollection('repository_activity');
db.repositories.createIndex({ 'repo_id': 1 }, { unique: true });
db.repositories.createIndex({ 'full_name': 1 }, { unique: true });
db.repositories.createIndex({ 'owner': 1 });
db.repositories.createIndex({ 'language': 1 });
db.repositories.createIndex({ 'stars': -1 });
db.repositories.createIndex({ 'updated_at': -1 });
db.repository_activity.createIndex({ 'repo_id': 1 });
db.repository_activity.createIndex({ 'timestamp': -1 });
db.repository_activity.createIndex({ 'activity_type': 1 });
print(' Cosmos DB initialized');
