#!/usr/bin/env python3
"""Generate a Markdown coverage report for the MCP layer from coverage.xml.

This version is tolerant of Windows paths and different coverage XML layouts.
It finds MCP-related files by flexible path matching instead of relying on a
single strict prefix.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class FileCoverage:
    filename: str
    covered: int
    total: int
    missing_lines: list[int]

    @property
    def percent(self) -> float:
        if self.total == 0:
            return 100.0
        return (self.covered / self.total) * 100.0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Markdown coverage report for the MCP layer."
    )
    parser.add_argument(
        "--coverage-xml",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to the Cobertura XML file generated by pytest-cov.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/MCP_COVERAGE.md"),
        help="Where to write the Markdown coverage report.",
    )
    parser.add_argument(
        "--prefix",
        type=str,
        default="src/mcp/",
        help="Preferred MCP scope prefix. Used as a hint, not a strict rule.",
    )
    return parser.parse_args()


def normalize_path(value: str) -> str:
    return value.replace("\\", "/").strip()


def is_mcp_file(filename: str, prefix: str) -> bool:
    normalized = normalize_path(filename)
    normalized_prefix = normalize_path(prefix).rstrip("/")

    # First try the requested prefix exactly.
    if normalized_prefix and normalized_prefix in normalized:
        return True

    # Fallbacks for common coverage layouts.
    lowered = normalized.lower()
    return (
        "/mcp/" in lowered
        or lowered.endswith("/mcp.py")
        or lowered.endswith("mcp.py")
        or lowered.startswith("mcp/")
        or "/src/mcp/" in lowered
    )


def extract_file_coverages(root: ET.Element, prefix: str) -> list[FileCoverage]:
    report: list[FileCoverage] = []

    # Normal pytest-cov Cobertura XML stores files under <class filename="...">.
    # We also accept any nested structure that contains class nodes.
    for class_node in root.findall(".//class"):
        filename = class_node.attrib.get("filename", "")
        if not filename:
            continue

        if not is_mcp_file(filename, prefix):
            continue

        line_nodes = class_node.findall("./lines/line")
        total = len(line_nodes)
        covered = 0
        missing_lines: list[int] = []

        for line in line_nodes:
            hits = int(line.attrib.get("hits", "0"))
            number = int(line.attrib["number"])
            if hits > 0:
                covered += 1
            else:
                missing_lines.append(number)

        report.append(
            FileCoverage(
                filename=normalize_path(filename),
                covered=covered,
                total=total,
                missing_lines=missing_lines,
            )
        )

    # If nothing matched, provide a helpful error with sample filenames.
    if not report:
        all_filenames = []
        for class_node in root.findall(".//class"):
            filename = class_node.attrib.get("filename", "")
            if filename:
                all_filenames.append(normalize_path(filename))

        sample = "\n".join(f"- {name}" for name in all_filenames[:20])
        raise RuntimeError(
            "No MCP files were found in coverage.xml.\n"
            "The first filenames seen in the XML were:\n"
            f"{sample if sample else '- <no class filenames found>'}"
        )

    return report


def build_markdown(report: list[FileCoverage], source_xml: Path, prefix: str) -> str:
    total_lines = sum(item.total for item in report)
    covered_lines = sum(item.covered for item in report)
    overall_percent = (covered_lines / total_lines * 100.0) if total_lines else 100.0

    lines: list[str] = []
    lines.append("# MCP coverage report")
    lines.append("")
    lines.append(f"Source: `{source_xml.as_posix()}`")
    lines.append(f"Scope hint: `{prefix}`")
    lines.append("")
    lines.append(
        f"Overall MCP line coverage: **{overall_percent:.1f}%** "
        f"({covered_lines}/{total_lines} lines)"
    )
    lines.append("")
    lines.append("## File breakdown")
    lines.append("")
    lines.append("| File | Covered | Total | Coverage | Missing lines |")
    lines.append("| --- | ---: | ---: | ---: | --- |")

    for item in sorted(report, key=lambda x: x.filename):
        missing = ", ".join(str(n) for n in item.missing_lines) if item.missing_lines else "—"
        lines.append(
            f"| `{item.filename}` | {item.covered} | {item.total} | "
            f"{item.percent:.1f}% | {missing} |"
        )

    lines.append("")
    lines.append("## What remains uncovered")
    lines.append("")
    uncovered_any = False
    for item in sorted(report, key=lambda x: x.filename):
        if not item.missing_lines:
            continue
        uncovered_any = True
        lines.append(f"- `{item.filename}`: lines {', '.join(str(n) for n in item.missing_lines)}")

    if not uncovered_any:
        lines.append("- No uncovered lines detected in the MCP scope.")

    lines.append("")
    lines.append("## How to regenerate")
    lines.append("")
    lines.append("```bash")
    lines.append("pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing")
    lines.append(
        "python scripts/report_mcp_coverage.py "
        "--coverage-xml coverage.xml --output docs/MCP_COVERAGE.md --prefix src/mcp/"
    )
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    if not args.coverage_xml.exists():
        print(f"ERROR: coverage XML not found: {args.coverage_xml}", file=sys.stderr)
        return 2

    try:
        tree = ET.parse(args.coverage_xml)
    except ET.ParseError as exc:
        print(f"ERROR: failed to parse {args.coverage_xml}: {exc}", file=sys.stderr)
        return 2

    root = tree.getroot()

    try:
        report = extract_file_coverages(root, args.prefix)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 3

    markdown = build_markdown(report, args.coverage_xml, args.prefix)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown, encoding="utf-8")

    total_lines = sum(item.total for item in report)
    covered_lines = sum(item.covered for item in report)
    percent = (covered_lines / total_lines * 100.0) if total_lines else 100.0

    print(
        f"Wrote {args.output} "
        f"({percent:.1f}% MCP line coverage, {covered_lines}/{total_lines} lines)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())